# Generated by victor lara

from django.db import migrations

def forwards_func(apps, schema_editor):
    permission = apps.get_model("permission", "Permission")
    
    permission.objects.bulk_create([
        permission(keyword="lectura", description="Poder ver los listados"),
        permission(keyword="escritura", description="Poder crear nuevos registros"),
        permission(keyword="admin", description="Todos los accesos"),
    ])

def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
